int _putchar(char c);
int _isupport(int c);
int _isdigital int c);
int mul(int a, int b);
void print_number(void);
void print_most_number(void);
void more_numbers(void);
void print_line(int n);
void print_digonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
